### ISSUE TITLE
After upgrading to 5.1.0  retrieving balance using custom properties as keys returns 0

### ISSUE THREAD

**Issue by cycleguy** [flash-oss/medici#58] opened 2022-01-25 17:17 UTC
@koresar 
Thank you for this module.

We have created a test program that demonstrates this.  We have introduced two custom properties: _businessId and _assetId.  

- Without using a custom schema  retrieving a book balance using these custom properties as keys returns the correct result.  
- When using a custom schema (line 15 in app.js is uncommented), retrieving book balance without using any of the custom properties works correctly (see _retrieveBalance() in app.js), but retrieving balance using either one or two of the custom properties as keys returns 0 (see _retrieveBalanceWithCustomProperties1() and _retrieveBalanceWithCustomProperties2() in app.js)

For the 3 test cases the correct balance should be

- -2000 for _retrieveBalance()
- 2000 for both _retrieveBalanceWithCustomProperties1() and _retrieveBalanceWithCustomProperties2()

To run without custom schema defined (ensure line 15 in app.js is commented out)
Tun run with custom schema defined (ensure line 15 in app.js is uncommented)

Possibly we are doing something wrong in our schema definition.  Thanks in advance for your help.

[medici-v5.zip](https://github.com/flash-oss/medici/files/7935700/medici-v5.zip)

**Comment by Uzlopak** [comment] 2022-01-25 17:41
The implicit registration of Schemas is obsolete with medici v5. you have to write a mongoose schema and use setTransactionSchema use as first parameter the Schema. Based on the Schema, medici v5 determines if it is a meta key or root key. As you did not assigned it, medici tries to search for _businessId and _assetId in the meta field and not on the root field

Also be aware: In medici v4 there was an implicit transformation of all vaues to ObjectIds if the key was starting with an `_`.  Now based on the Schema, we determine if it is an ObjectId or not.

**Comment by cycleguy** [comment] 2022-01-25 18:58
We have written a mongoose schema and we are using setTransactionSchema within the mediciTransaction.js file.  You mentioned that we did not assign it, what exactly are you referring to?  Thanks.

**Comment by Uzlopak** [comment] 2022-01-25 19:15
In your zipfile you don't call setTransactionSchema.

**Comment by cycleguy** [comment] 2022-01-25 19:43
I double checked the zip file that I sent you....

- On line 15 of app.js (if uncommented out) does a require on ./models/mediciTransaction
- On line 41 of mediciTransaction.js it calls setTransactionSchema()

- src/app.js
- src/index.js
- src/models/mediciTransaction.js

**Comment by dolcalmi** [comment] 2022-01-26 06:43
We have the same issue, I think is a problem in `parseBalanceQuery` https://github.com/flash-oss/medici/blob/master/src/helper/parse/parseBalanceQuery.ts#L38 should use the same logic used in `parseFilterQuery` https://github.com/flash-oss/medici/blob/master/src/helper/parse/parseFilterQuery.ts#L52

**Comment by cycleguy** [comment] 2022-01-26 18:37
Thank you in advance @dolcalmi for taking the time to fix this issue.

**Comment by koresar** [comment] 2022-01-27 06:58
The difference exists because the balance query (not the balance, but the query JSON) is being serialised to a single string as a Quick Balance cache key: https://github.com/flash-oss/medici/blob/12dd0b3b778cd0341a1492020323da4b7d4bb971/src/models/balance.ts#L48

The key is being constructed wrongly when schema is not native and you query by our own keys.

Quick workarounds would be to disable Quick Balance feature. Pass `balanceSnapshotSec` as zero:
 `new Book(name, { balanceSnapshotSec: 0 });`

**Comment by dolcalmi** [comment] 2022-01-27 15:13
this is not the only issue, the problem is how the query is parsed. I will work on it today

**Comment by dolcalmi** [comment] 2022-07-06 17:53
@koresar this can be closed once the new version is released

**Comment by koresar** [comment] 2022-07-08 02:18
Published in v5.2

**Closed by koresar** 2022-07-08 02:18 UTC
